version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
 

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

volumes:
  mssql_data: