version: '3.4'

services:

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest  

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Dockerfile
    
volumes:
  orderdb_data: