version: '3.4'

services:
  orderdb:
    container_name: orderdb
    environment:
        - SA_PASSWORD=ordering123
        - ACCEPT_EULA=Y
    restart: always
    ports:
        - "1433:1433"
    volumes:
        - orderdb_data:/var/opt/mssql/data
  
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


